const express = require('express');
const cors = require('cors');
const mysql = require('mysql2/promise');
const axios = require('axios');

require('dotenv').config();

const app = express();
app.use(express.json());
app.use(cors());

// Service port
const PORT = Number(process.env.PORT || 5002);

// Inventory service base URL (Order Service depends on Inventory for stock checks and prices)
const INVENTORY_SERVICE_URL = process.env.INVENTORY_SERVICE_URL;

if (!INVENTORY_SERVICE_URL) {
    // Warn during startup so the developer knows the service is misconfigured locally
    console.warn('⚠️  INVENTORY_SERVICE_URL is not set. POST /api/orders will fail until configured.');
}

// Database connection (MySQL) using mysql2/promise (async/await)
const dbConfig = {
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    port: process.env.DB_PORT ? Number(process.env.DB_PORT) : 3306,
    waitForConnections: true,
    connectionLimit: 10,
    queueLimit: 0
};

const pool = mysql.createPool(dbConfig);


function validateCreateOrderPayload(body) {
    if (!body || typeof body !== 'object') {
        return { ok: false, message: 'Request body must be a JSON object.' };
    }

    const { items, customer_name } = body;

    if (customer_name !== undefined && customer_name !== null && typeof customer_name !== 'string') {
        return { ok: false, message: 'customer_name must be a string when provided.' };
    }

    if (!Array.isArray(items) || items.length === 0) {
        return { ok: false, message: 'items must be a non-empty array.' };
    }

    for (const item of items) {
        if (!item || typeof item !== 'object') {
            return { ok: false, message: 'Each item must be an object.' };
        }

        const { product_id, quantity } = item;

        if (!Number.isInteger(product_id) || product_id <= 0) {
            return { ok: false, message: 'Each item.product_id must be a positive integer.' };
        }

        if (!Number.isInteger(quantity) || quantity <= 0) {
            return { ok: false, message: 'Each item.quantity must be a positive integer.' };
        }
    }

    return { ok: true };
}

// Fetch product list from the Inventory Service.
// Used to read current prices (Inventory is the source of truth for catalog data).
async function fetchInventoryProducts() {
    const response = await axios.get(`${INVENTORY_SERVICE_URL}/api/products`, { timeout: 5000 });
    return Array.isArray(response.data) ? response.data : [];
}

/**
 * HELPER 1: CONSOLIDATE ITEMS
 * Combines duplicate product entries in the incoming user cart.
 * * Why this is useful: If a user sends a payload with the same product ID split 
 * across multiple lines, this merges them in-memory to prevent duplicate database 
 * operations or redundant API checks later.
 * * @param {Array} items - Raw array of cart items from req.body (e.g., [{product_id: 1, quantity: 2}, ...])
 * @returns {Map} A Map linking unique product IDs (Key) to their total combined quantities (Value)
 */
function consolidateItems(items) {
    // A Map is used for quick  lookups and updates
    const requestedQtyById = new Map();

    for (const item of items) {
        const productId = Number(item.product_id);
        const quantity = Number(item.quantity);
        
        // Look up if we've already tracked this product in our Map.
        // If it doesn't exist yet, default its current quantity to 0.
        const currentQty = requestedQtyById.get(productId) || 0;
        
        // Add the new quantity onto the existing total and update the Map
        requestedQtyById.set(productId, currentQty + quantity);
    }

    return requestedQtyById;
}

/**
 * HELPER 2: BUILD ORDER DATA
 * Matches the user's requested cart against the official catalog price list, 
 * validates the financial values, and formats the payloads for both local DB and remote services.
 * * @param {Map} requestedQtyById - The clean Map generated by consolidateItems()
 * @param {Map} productById - The official product catalog map fetched from the Inventory Service
 * @returns {Object} An object containing status flags, computed totals, and tailored payloads
 */
function buildOrderData(requestedQtyById, productById) {
    const orderItems = [];      // Rows tailored for our local 'order_items' SQL table
    const inventoryItems = [];  // Minified payload tailored for the external 'inventory-service'

    // Loop through every unique item the customer wants to buy
    for (const [productId, quantity] of requestedQtyById.entries()) {
        // Fetch the corresponding product profile from the official inventory catalog map
        const product = productById.get(productId);

        // DATA VALIDATION: If the user passed an ID that doesn't exist in our active catalog, abort.
        if (!product) {
            return {
                ok: false,
                message: `Unknown product_id or missing price for product_id=${productId}.`
            };
        }

        const unitPrice = Number(product.price);

        // DATA VALIDATION: Ensure the price is a valid, real number (e.g., not NaN, null, or undefined)
        if (!Number.isFinite(unitPrice)) {
            return {
                ok: false,
                message: `Invalid price for product_id=${productId}.`
            };
        }

        // Format and push the row needed to populate our local MySQL database
        orderItems.push({
            product_id: productId,
            quantity,
            unit_price: unitPrice
        });

        // Format and push the minimal data array needed by the Inventory Service endpoint
        inventoryItems.push({
            id: productId,
            quantity
        });
    }

    // FINANCIAL CALCULATION: Aggregate line-item totals using Array.reduce()
    // Accumulator formula: sum = sum + (price * quantity)
    const totalAmount = roundTo2(
        orderItems.reduce((sum, item) => sum + item.unit_price * item.quantity, 0)
    );

    // Return everything packaged up cleanly for the main endpoint controller to use
    return {
        ok: true,
        orderItems,
        inventoryItems,
        totalAmount
    };
}

/**
 * HELPER 3: ROUND TO 2 DECIMAL PLACES
 * Solves JavaScript's native floating-point math issues (e.g., 0.1 + 0.2 = 0.30000000000000004).
 * * How it works: Multiplies the number by 100 to shift the decimals out of the way,
 * rounds it to the nearest whole integer, and then shifts the decimal back by dividing by 100.
 * * @param {Number} amount - The unrounded calculated sum
 * @returns {Number} Financial total rounded precisely to two decimal places
 */
function roundTo2(amount) {
    return Math.round(Number(amount) * 100) / 100;
}

// Health check endpoint
// - Returns 200 when the service and DB are reachable
// - Useful for load-balancers and basic manual verification
app.get('/', async (req, res) => {
    try {
        await pool.query('SELECT 1');
        return res.status(200).json({
            status: 'ok',
            service: 'order-service',
            db: 'ok',
            time: new Date().toISOString()
        });
    } catch (err) {
        return res.status(500).json({
            status: 'error',
            service: 'order-service',
            db: 'error',
            message: err.message
        });
    }
});

/**
 * GET /api/orders
 * Return order history (orders and their items) from the Order Service database.
 * The SQL produces a flat join result which we reshape into a nested JSON structure.
 */
app.get('/api/orders', async (req, res) => {
    try {
        const [rows] = await pool.query(
            `SELECT
                o.id AS order_id,
                o.customer_name,
                o.total_amount,
                o.created_at,
                oi.id AS order_item_id,
                oi.product_id,
                oi.quantity,
                oi.unit_price
            FROM orders o
            LEFT JOIN order_items oi ON oi.order_id = o.id
            ORDER BY o.created_at DESC, oi.id ASC`
        );

        // Convert the flat JOIN result into a nested JSON structure:
        // [ { id, customer_name, total_amount, created_at, items: [...] }, ... ]
        const ordersById = new Map();

        for (const row of rows) {
            if (!ordersById.has(row.order_id)) {
                ordersById.set(row.order_id, {
                    id: row.order_id,
                    customer_name: row.customer_name,
                    total_amount: Number(row.total_amount),
                    created_at: row.created_at,
                    items: []
                });
            }

            // If there are no items for an order ,
            // LEFT JOIN will return nulls
            if (row.order_item_id) {
                ordersById.get(row.order_id).items.push({
                    id: row.order_item_id,
                    product_id: row.product_id,
                    quantity: row.quantity,
                    unit_price: Number(row.unit_price)
                });
            }
        }

        return res.status(200).json({
            success: true,
            orders: Array.from(ordersById.values())
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'Failed to fetch order history.',
            error: err.message
        });
    }
});


/**
 * POST /api/orders
 * Create a new order.
 */
app.post('/api/orders', async (req, res) => {
    // STEP 1: INITIAL REQUEST VALIDATION
    const validation = validateCreateOrderPayload(req.body);
    if (!validation.ok) {
        return res.status(400).json({ success: false, message: validation.message });
    }

    if (!INVENTORY_SERVICE_URL) {
        return res.status(500).json({
            success: false,
            message: 'Order Service misconfiguration: INVENTORY_SERVICE_URL is missing.'
        });
    }

    // STEP 2: CONSOLIDATE CLIENT QUANTITIES
    // Merge duplicate product entries so we operate on aggregated quantities
    const requestedQtyById = consolidateItems(req.body.items);

    try {
        // STEP 3: FETCH CATALOG DATA & BUILD ORDER
        // Fetch product prices from Inventory (source of truth) and prepare order payloads
        const products = await fetchInventoryProducts();
        const productById = new Map(products.map((p) => [Number(p.id), p]));
        const orderData = buildOrderData(requestedQtyById, productById);

        if (!orderData.ok) {
            return res.status(400).json({ success: false, message: orderData.message });
        }

        // STEP 4: REMOTE INVENTORY VALIDATION (and deduction)
        // Ask Inventory Service to validate stock (it runs its own transactional deduction)
        const stockResponse = await axios.post(
            `${INVENTORY_SERVICE_URL}/api/products/validate-stock`,
            { items: orderData.inventoryItems },
            { timeout: 5000 }
        );

        // STEP 5: PERSIST ORDER LOCALLY (single DB transaction)
        // Use a bulk insert for order items to reduce network roundtrips (O(1) per order)
        let connection;
        try {
            connection = await pool.getConnection();
            await connection.beginTransaction();

            const customerName = req.body.customer_name || null;

            // Insert order header
            const [orderResult] = await connection.query(
                'INSERT INTO orders (customer_name, total_amount) VALUES (?, ?)',
                [customerName, orderData.totalAmount]
            );

            const orderId = orderResult.insertId;

            // Prepare bulk rows: [order_id, product_id, quantity, unit_price]
            const orderItemRows = orderData.orderItems.map((it) => [orderId, it.product_id, it.quantity, it.unit_price]);

            if (orderItemRows.length > 0) {
                // Single bulk INSERT using parameter placeholder for multiple rows
                await connection.query(
                    'INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES ?',
                    [orderItemRows]
                );
            }

            await connection.commit();

            // STEP 6: FINAL RESPONSE
            return res.status(201).json({
                success: true,
                message: 'Order created successfully.',
                order: {
                    id: orderId,
                    customer_name: customerName,
                    total_amount: orderData.totalAmount,
                    items: orderData.orderItems
                },
                inventory: stockResponse.data
            });
        } catch (dbErr) {
            // Attempt to rollback the DB transaction locally
            if (connection) {
                try {
                    await connection.rollback();
                } catch (_) {}
            }

            // COMPENSATING ACTION: Inventory was already deducted by the Inventory Service
            // before we attempted to persist the local order. If the local DB failed,
            // we must attempt to restore stock by calling the Inventory Service's
            // `/api/products/release-stock` endpoint with the same items.
            try {
                await axios.post(
                    `${INVENTORY_SERVICE_URL}/api/products/release-stock`,
                    { items: orderData.inventoryItems },
                    { timeout: 5000 }
                );
            } catch (releaseErr) {
                // Log the compensating rollback failure - this is important for
                // operators to detect and reconcile inventory/order mismatch.
                try {
                    console.error('Compensating rollback failed: unable to release inventory after DB error.',
                        releaseErr.response ? releaseErr.response.data : releaseErr.message || releaseErr);
                } catch (logErr) {
                    // Ensure logging itself never throws
                    console.error('Error while logging compensating rollback failure:', logErr);
                }
            }

            return res.status(500).json({ success: false, message: 'Failed to create order due to a database error.', error: dbErr.message });
        } finally {
            if (connection) connection.release();
        }
    } catch (err) {
        // If Inventory Service returned a structured error, forward that response
        if (err.response) {
            return res.status(err.response.status).json({ success: false, message: 'Inventory check failed.', inventory: err.response.data });
        }

        // Generic fallback when Inventory Service is unreachable
        return res.status(503).json({ success: false, message: 'Inventory Service is unavailable. Please try again later.' });
    }
});

// Return JSON 404 for unknown routes
app.use((req, res) => {
    return res.status(404).json({
        success: false,
        message: 'Route not found.'
    });
});

// Graceful shutdown handler
async function shutdown(signal) {
    try {
        console.log(`\n${signal} received: closing DB pool...`);
        await pool.end();
        console.log('DB pool closed. Exiting.');
        process.exit(0);
    } catch (err) {
        console.error('Error during shutdown:', err);
        process.exit(1);
    }
}

process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

app.listen(PORT, () => {
    console.log(`✅ Order Service is running on http://localhost:${PORT}`);
});
